// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdate(arg1, arg2, arg3) {
  return window['go']['main']['App']['CheckForUpdate'](arg1, arg2, arg3);
}

export function ComposeDown(arg1) {
  return window['go']['main']['App']['ComposeDown'](arg1);
}

export function ComposeUp(arg1) {
  return window['go']['main']['App']['ComposeUp'](arg1);
}

export function CreateNetwork(arg1) {
  return window['go']['main']['App']['CreateNetwork'](arg1);
}

export function CreateSecret(arg1, arg2) {
  return window['go']['main']['App']['CreateSecret'](arg1, arg2);
}

export function CreateVolume(arg1) {
  return window['go']['main']['App']['CreateVolume'](arg1);
}

export function EncodeRegistryAuth(arg1) {
  return window['go']['main']['App']['EncodeRegistryAuth'](arg1);
}

export function GetContainerHealth(arg1) {
  return window['go']['main']['App']['GetContainerHealth'](arg1);
}

export function GetContainerStats(arg1) {
  return window['go']['main']['App']['GetContainerStats'](arg1);
}

export function GetDockerStatus() {
  return window['go']['main']['App']['GetDockerStatus']();
}

export function GetSwarmOverview() {
  return window['go']['main']['App']['GetSwarmOverview']();
}

export function InspectComposeFile(arg1) {
  return window['go']['main']['App']['InspectComposeFile'](arg1);
}

export function InspectContainer(arg1) {
  return window['go']['main']['App']['InspectContainer'](arg1);
}

export function ListCIWorkflowRuns(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListCIWorkflowRuns'](arg1, arg2, arg3);
}

export function ListContainers() {
  return window['go']['main']['App']['ListContainers']();
}

export function ListDemoContainers() {
  return window['go']['main']['App']['ListDemoContainers']();
}

export function ListImages() {
  return window['go']['main']['App']['ListImages']();
}

export function ListNetworks() {
  return window['go']['main']['App']['ListNetworks']();
}

export function ListRegistryCatalog(arg1) {
  return window['go']['main']['App']['ListRegistryCatalog'](arg1);
}

export function ListRegistryTags(arg1, arg2) {
  return window['go']['main']['App']['ListRegistryTags'](arg1, arg2);
}

export function ListSecrets() {
  return window['go']['main']['App']['ListSecrets']();
}

export function ListSwarmServices() {
  return window['go']['main']['App']['ListSwarmServices']();
}

export function ListVolumes() {
  return window['go']['main']['App']['ListVolumes']();
}

export function OpenContainerInBrowser(arg1) {
  return window['go']['main']['App']['OpenContainerInBrowser'](arg1);
}

export function OpenExternalURL(arg1) {
  return window['go']['main']['App']['OpenExternalURL'](arg1);
}

export function PullImage(arg1) {
  return window['go']['main']['App']['PullImage'](arg1);
}

export function RemoveContainer(arg1, arg2) {
  return window['go']['main']['App']['RemoveContainer'](arg1, arg2);
}

export function RemoveImage(arg1, arg2) {
  return window['go']['main']['App']['RemoveImage'](arg1, arg2);
}

export function RemoveNetwork(arg1) {
  return window['go']['main']['App']['RemoveNetwork'](arg1);
}

export function RemoveSecret(arg1) {
  return window['go']['main']['App']['RemoveSecret'](arg1);
}

export function RemoveVolume(arg1, arg2) {
  return window['go']['main']['App']['RemoveVolume'](arg1, arg2);
}

export function RestartContainer(arg1) {
  return window['go']['main']['App']['RestartContainer'](arg1);
}

export function ScanImage(arg1) {
  return window['go']['main']['App']['ScanImage'](arg1);
}

export function SelectComposeFile() {
  return window['go']['main']['App']['SelectComposeFile']();
}

export function StartContainer(arg1) {
  return window['go']['main']['App']['StartContainer'](arg1);
}

export function StartContainerLogStream(arg1) {
  return window['go']['main']['App']['StartContainerLogStream'](arg1);
}

export function StopContainer(arg1) {
  return window['go']['main']['App']['StopContainer'](arg1);
}

export function StopContainerLogStream(arg1) {
  return window['go']['main']['App']['StopContainerLogStream'](arg1);
}

export function TestRegistryConnection(arg1) {
  return window['go']['main']['App']['TestRegistryConnection'](arg1);
}
