// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckForUpdate(arg1:string,arg2:string,arg3:string):Promise<main.UpdateCheckResult>;

export function ComposeDown(arg1:string):Promise<void>;

export function ComposeUp(arg1:string):Promise<void>;

export function CreateNetwork(arg1:string):Promise<main.NetworkInfo>;

export function CreateSecret(arg1:string,arg2:string):Promise<main.SecretInfo>;

export function CreateVolume(arg1:string):Promise<main.VolumeInfo>;

export function EncodeRegistryAuth(arg1:main.RegistryAuthConfig):Promise<string>;

export function GetContainerHealth(arg1:string):Promise<string>;

export function GetContainerStats(arg1:string):Promise<main.ContainerStats>;

export function GetDockerStatus():Promise<main.DockerStatus>;

export function GetSwarmOverview():Promise<main.SwarmOverview>;

export function InspectComposeFile(arg1:string):Promise<main.ComposeProjectSummary>;

export function InspectContainer(arg1:string):Promise<main.ContainerDetails>;

export function ListCIWorkflowRuns(arg1:string,arg2:string,arg3:string):Promise<main.CIWorkflowRunResult>;

export function ListContainers():Promise<Array<main.ContainerInfo>>;

export function ListDemoContainers():Promise<Array<main.ContainerInfo>>;

export function ListImages():Promise<Array<main.ImageInfo>>;

export function ListNetworks():Promise<Array<main.NetworkInfo>>;

export function ListRegistryCatalog(arg1:main.RegistryConfig):Promise<main.RegistryCatalogResult>;

export function ListRegistryTags(arg1:main.RegistryConfig,arg2:string):Promise<main.RegistryTagsResult>;

export function ListSecrets():Promise<Array<main.SecretInfo>>;

export function ListSwarmServices():Promise<Array<main.SwarmServiceInfo>>;

export function ListVolumes():Promise<Array<main.VolumeInfo>>;

export function OpenContainerInBrowser(arg1:string):Promise<void>;

export function OpenExternalURL(arg1:string):Promise<void>;

export function PullImage(arg1:string):Promise<void>;

export function RemoveContainer(arg1:string,arg2:boolean):Promise<void>;

export function RemoveImage(arg1:string,arg2:boolean):Promise<void>;

export function RemoveNetwork(arg1:string):Promise<void>;

export function RemoveSecret(arg1:string):Promise<void>;

export function RemoveVolume(arg1:string,arg2:boolean):Promise<void>;

export function RestartContainer(arg1:string):Promise<void>;

export function ScanImage(arg1:string):Promise<main.ImageScanResult>;

export function SelectComposeFile():Promise<string>;

export function StartContainer(arg1:string):Promise<void>;

export function StartContainerLogStream(arg1:string):Promise<void>;

export function StopContainer(arg1:string):Promise<void>;

export function StopContainerLogStream(arg1:string):Promise<void>;

export function TestRegistryConnection(arg1:main.RegistryConfig):Promise<void>;
